category: kalan
points: 1
title: Всё тайное становится явным
sort_key: k11
author: teamteam
description: >
  <p>
    По нашим слухам, на встрече директор лично проводит эксперименты. Калан точно там! Сообщите его местоположение — он не должен успеть убежать.
  </p>
  <p>
    Нам известно, что локации офиса помечены некими кодовыми словами. Сдайте соответствующее локации слово.
  </p>
flags:
  - "Интересно"
depends_on: meeting
